### ISSUE TITLE
NEC Aurora Optimization bugs

### ISSUE THREAD

**Issue by kruus** [necla-ml/gen-dnn#5]
## Low Priority TODO
- [ ] Clean up code: code unreadable with #if..#pragma..#else..#pragma..#endif clutter
  - [x] Try __Pragma macro approach
  - [ ] Try awk transforms to produce __ve/_SX/LINUX system-specific .cpp files
- [ ] -O2 ? remove -ffast-math ? (dumb down the "safe" compiler flags).

### Description
Some Benchdnn impls run correctly under gcc-5, gcc-7 and sxcc, but produce wrong
results for ncc at default Release flags (-O3 -ffast-math, ...)

### Environment
ncc version 0.21 or 0.23

### Steps to reproduce
./build.sh -qaT # on zoro or aurora (possibly different ncc versions).
./regr.sh ALL   # on aurora, to ve_exec the cross-compiled binaries

### Actual behavior
test failures : ref_conv4 was disabled for __ve and now sx_conv3 BWD_D is not
able to run correctly.  Checked many git versions on x86 and ncc, but did not find
any that ran correctly on Aurora. 

### Expected behavior
Zero test failures (and still no failures if ref_conv4 tests are reintroduced).

**Comment by kruus** [comment]
Ahaa. Some SX alloc_on_vreg pragmas have been incorrectly translated to vreg on Aurora. This might explain some of the issues. (SX-ACE had a large number of registers, so this approach could handle pretty long arrays).

**Comment by efocht** [comment]
Maybe a case for keeping things in LLC:
```
#pragma _NEC retain(<arrayname>)
```
You'll need the compiler option -mretain-list-vector or -mretain-none to really have higher retention priority.

**Comment by kruus** [comment]
Good idea. There were already some retains from Chris.
So far, _Pragma macros look like they'll restore code readability
(fingers crossed). I'll try having SX on_adb macro "decay" into
a retain on aurora.

**Comment by kruus** [comment]
[common.hpp](https://github.com/necla-ml/gen-dnn/blob/master/tests/benchdnn/common.hpp) encapsulates system-specific #pragmas by using macros to emit _Pragma(...) constructs, which are a c++11 feature.  This makes code readable/maintainable again.

Removing all optimization **and** omp macros for Aurora still fails the tests, so this seems
to be an *nc++* compiler bug (with no short testcase, for now)

Temporarily "fixed" in [f0c4522](https://github.com/necla-ml/gen-dnn/commit/f0c45223b1e98c51950d507d2d9164a786d94fed)
by reverting to dumber impls

**Comment by efocht** [comment]
I've updated my environment to 0.4.0 (veos and the rest of stuff coming from the tsubasa repository). Using a manually installed cmake-3.10.1 now but with no success. Something is broken for me, compilation doesn't get through on Aurora.

```
Compiling CXX source to assembly CMakeFiles/benchdnn.dir/conv/sx_conv4.cpp.s
cd /home/focht/gen-dnn/build/tests/benchdnn && /opt/nec/ve/bin/nc++ -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -DSXAURORA -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/home/focht/gen-dnn/include -I/home/focht/gen-dnn/tests/benchdnn -I/home/focht/gen-dnn/tests/benchdnn/conv -I/home/focht/gen-dnn/tests/benchdnn/ip -I/home/focht/gen-dnn/tests/benchdnn/self -I/home/focht/gen-dnn/tests/benchdnn/self/conv  -DUSE_CBLAS -DTARGET_VANILLA -DCBLAS_LAYOUT=CBLAS_ORDER -proginf -Wall -std=gnu++11 -DUSE_CBLAS -DTARGET_VANILLA -DCBLAS_LAYOUT=CBLAS_ORDER -proginf -Wall -std=c99 -O3 -finline -finline-functions -fdiag-parallel=2 -ffast-math -DUSE_CBLAS -DTARGET_VANILLA -DCBLAS_LAYOUT=CBLAS_ORDER -proginf -Wall -std=c99 -O3 -finline -finline-functions -fdiag-parallel=2 -ffast-math   -Wno-error -O3 -DNDEBUG -D_FORTIFY_SOURCE=2   -std=gnu++11 -g  -Wa,-adhln -c /home/focht/gen-dnn/tests/benchdnn/conv/sx_conv4.cpp -o /dev/null > CMakeFiles/benchdnn.dir/conv/sx_conv4.cpp.s.0
ccom: Warning: '-std=c99' is valid for C but not for C++
ccom: Warning: '-std=c99' is valid for C but not for C++
"/home/focht/gen-dnn/tests/benchdnn/common.hpp", line 113: warning: #warning
          directive: "__ve optimization pragmas IN EFFECT"
  #warning "__ve optimization pragmas IN EFFECT"
   ^

"/home/focht/gen-dnn/tests/benchdnn/conv/sx_conv4.cpp", line 563: error:
          identifier "_NEC" is undefined
      VREG(khkw_begend)
      ^

"/home/focht/gen-dnn/tests/benchdnn/conv/sx_conv4.cpp", line 563: error:
          expected a ")"
      VREG(khkw_begend)
      ^

"/home/focht/gen-dnn/tests/benchdnn/conv/sx_conv4.cpp", line 563: error:
          identifier "Str" is undefined
      VREG(khkw_begend)
      ^

"/home/focht/gen-dnn/tests/benchdnn/conv/sx_conv4.cpp", line 563: error:
          identifier "ZPragma" is undefined
      VREG(khkw_begend)
```

**Comment by kruus** [comment]
All 3 compilers deal with the macro expansion differently. Will look at it again now. Thx for report.

**Comment by efocht** [comment]
Compiler version is 0.0.23

**Comment by kruus** [comment]
Yup, I did not commit the right stuff yesterday. I verified the issues.  Will fix [again] later tonight. Time to see Star Wars!

**Comment by kruus** [comment]
Fixed in [3af8d73b](https://github.com/necla-ml/gen-dnn/commit/3af8d73b0c219285e56e6f1ede78a1710a7144b5).  Yesterday I pulled from a bad remote and lost some of my mods.  I redid them, I think better this time around.  On some compilers the pragma usage is still questionable (esp. SX).

**Comment by efocht** [comment]
Excellent! It builds now. Thanks.

**Comment by kruus** [comment]
To increase chances of correct compilation, nc++ likes to have declaration of local runtime-sized arrays near the top of their scope [function].  This allowed sx_conv3 code to work correctly again. The same thing still did not fix the wrong compilation in ref_conv4 on Aurora.

**Comment by kruus** [comment]
There are also openmp bugs if you have multiple `omp parallel` in a single function.
The workaround is to split the function into sections, each of which only has a single omp region.
