### ISSUE TITLE
FYI: upcomming changes in MKL-DNN reorders

### ISSUE THREAD

**Issue by emfomenk** [necla-ml/gen-dnn#7]
Just a heads up.

MKL-DNN developers are going to replace all our reorders with the jitted versions, cause we have too many formats (and hence reorders) now and a bunch of new is coming. So it becomes really hard to handle those and we decided to go with auto-generated version that would support arbitrary reorders (at least in theory).

Since gen-dnn doesn't rely on jit the only version that will remain is [ref any<->any](https://github.com/necla-ml/gen-dnn/blob/master/src/cpu/simple_reorder.hpp#L1546) that is used [here](https://github.com/necla-ml/gen-dnn/blob/master/src/cpu/cpu_reorder.cpp#L128).

Please let me know if you have any concerns -- we can try to make the change in way it would not affect you that much. For instance we can consider leaving C-code for some popular plain format transforms like `nchw <-> nhwc`. The only problem I see with this approach is that we are thinking on switching to another memory layout representation (which would cover 2+-level blocking, that is currently cannot be expressed in blocking_desc). If we do so it would be really hard to have some specialized plain-C reorder versions of transforms, but would be much simpler to generate the jitted code.

**Comment by kruus** [comment]
Sounds good to me. Just keeping ref any<->any is the right thing to do, I think ---  I'll plop "legacy" reorders [only a few, really, for examples/ and tests/] into my src/vanilla/.  Anyhow, thanks for the heads up, and asking about keeping more than strictly necessary.

The use of gen-dnn is mainly stop-gap to demonstrate the API on new platforms. As expected, only a few layers run efficiently with C/Blas available (convolution is not so bad after speeding up im2col a bit). Ideally (after sorting out thorny cross-compilation issues) we'll get a JIT assembler going and can begin providing faster jitted impls where most needed.  Btw, I'm liking API changes in the upstream merge I'm working on :)

**Comment by emfomenk** [comment]
oK, if you are fine with having `ref any <-> any` only -- that's cool.

Looking forward for your changes :)
